# https://github.com/bitnami/charts/blob/196f2e6feea2fd589d23b0bb111cb86202a2cb36/bitnami/metallb/values.yaml
metallb:
  controller:
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  speaker:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 25m
        memory: 25Mi
