apps:
  - name: wireguard
    namespace: services
    path: kubernetes/services/wireguard
    sync: true

  - name: diskstation
    namespace: services
    path: kubernetes/services/diskstation
    sync: true

  - name: adguard
    namespace: services
    path: kubernetes/services/adguard
    sync: true

  - name: home-assistant
    namespace: services
    path: kubernetes/services/home-assistant
    sync: true

  - name: paperless
    namespace: services
    path: kubernetes/services/paperless
    sync: true

  - name: jellyfin
    namespace: services
    path: kubernetes/services/jellyfin
    sync: true

  - name: kavita
    namespace: services
    path: kubernetes/services/kavita
    sync: true

  - name: unifi
    namespace: services
    path: kubernetes/services/unifi
    sync: true

  - name: coder
    namespace: coder-space
    path: kubernetes/services/coder
    sync: true

  - name: frigate
    namespace: services
    path: kubernetes/services/frigate
    sync: true

  - name: immich
    namespace: services
    path: kubernetes/services/immich
    sync: true

  - name: service-secrets
    namespace: services
    repoURL: git@github.com:seungbemi/gitops-secrets.git
    path: kubernetes/services/secrets
    sync: true
