apiVersion: v2
description: A Helm chart for jellyfin
name: jellyfin
version: 1.0.0
# https://github.com/jellyfin/jellyfin/releases
# renovate: image=jellyfin/jellyfin
appVersion: 10.9.10

dependencies:
  - name: common
    repository: https://bernd-schorgers.github.io/helm-charts 
    version: 3.4.0
