# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json
# https://github.com/bjw-s/helm-charts/blob/common-3.1.0/charts/library/common/values.yaml
controllers:
  main:
    containers:
      main:
        image:
          repository: jellyfin/jellyfin
          pullPolicy: IfNotPresent
          tag: "{{ .Chart.AppVersion }}"
        env:
          TZ: "Europe/Helsinki"
          JELLYFIN_DATA_DIR: "/data"
          JELLYFIN_CONFIG_DIR: "/config"
          JELLYFIN_CACHE_DIR: "/cache"
        envFrom:
        - secretRef:
            name: jellyfin-secrets
            optional: false
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
service:
  main:
    controller: main
    ports:
      http:
        port: 8096

persistence:
  data:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/jellyfin/data
    globalMounts:
      - path: /data
  cache:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/jellyfin/cache
    globalMounts:
      - path: /cache

  config:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/jellyfin/config
    globalMounts:
      - path: /config
  video:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume2/video
    advancedMounts:
      main:
        main:
        - path: /media/video
          readOnly: true
  music:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume2/music
    advancedMounts:
      main:
        main:
        - path: /media/music
          readOnly: true
resources:
  requests:
    cpu: 16m
    memory: 250Mi
