apiVersion: v2
name: coder
description: Remote development environments on your infrastructure
type: application

version: v2.1.5
appVersion: v2.1.5

dependencies:
- name: coder
  version: v2.1.5
  repository: https://helm.coder.com/v2
