apiVersion: v2
name: coder
description: Remote development environments on your infrastructure
type: application

version: v0.23.7
appVersion: v0.23.7

dependencies:
- name: coder
  version: v0.23.7
  repository: https://helm.coder.com/v2
