apiVersion: v2
name: coder
description: Remote development environments on your infrastructure
type: application
# https://github.com/coder/coder/releases
version: v2.12.3
appVersion: v2.12.3

dependencies:
- name: coder
  version: v2.12.3
  repository: https://helm.coder.com/v2
