# https://github.com/coder/coder/blob/v2.4.0/helm/coder/values.yaml
coder:
  coder:
    env:
      - name: CODER_PG_CONNECTION_URL
        valueFrom:
          secretKeyRef:
            name: coder-secrets
            key: db-url
      - name: CODER_ACCESS_URL
        valueFrom:
          secretKeyRef:
            name: coder-secrets
            key: access-url
    service:
      enable: true
      type: ClusterIP
    serviceAccount:
      workspacePerms: true
      enableDeployments: true
      extraRules:
        - apiGroups: [""]
          resources: ["services"]
          verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
        - apiGroups: ["networking.k8s.io"]
          resources: ["networkpolicies"]
          verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
