# https://github.com/coder/coder/blob/v0.19.2/helm/values.yaml
coder:
  coder:
    env:
      - name: CODER_PG_CONNECTION_URL
        valueFrom:
          secretKeyRef:
            name: coder-secrets
            key: db-url
      - name: CODER_ACCESS_URL
        valueFrom:
          secretKeyRef:
            name: coder-secrets
            key: access-url
    service:
      enable: true
      type: ClusterIP
