apiVersion: v2
description: A helm chart for pruning container images
name: image-pruner
version: 1.0.0
appVersion: "3.17.3"

dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.4.0
