# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.0.1/charts/library/common/values.yaml
defaultPodOptions:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule

controllers:
  main:
    type: daemonset
    containers:
      main:
        image:
          repository: alpine
          pullPolicy: IfNotPresent
          tag: latest
        command:
          [
            "sh",
            "-c",
            "wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$CRICTL_VERSION/crictl-$CRICTL_VERSION-linux-amd64.tar.gz && tar zxvf crictl-$CRICTL_VERSION-linux-amd64.tar.gz -C /usr/local/bin && crontab /config/cronjobs && crond -f -d 8",
          ]
        env:
          TZ: "Europe/Helsinki"
          CRICTL_VERSION: v1.25.0
          CONTAINER_RUNTIME_ENDPOINT: unix:///var/run/containerd/containerd.sock
          IMAGE_SERVICE_ENDPOINT: unix:///var/run/containerd/containerd.sock
        resources:
          requests:
            cpu: 100m
            memory: 50Mi


configMaps:
  config:
    enabled: true
    data:
      cronjobs: 0 3 1 * * crictl rmi --prune 2>&1
    

persistence:
  containerd:
    enabled: true
    type: hostPath
    hostPath: /var/run/containerd/containerd.sock
    hostPathType: Socket
    advancedMounts:
      main:
        main:
          - path: /var/run/containerd/containerd.sock
  config:
    enabled: true
    type: configMap
    name: image-pruner-config
