apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
spec:
  jobLabel: traefik
  selector:
    matchLabels:
      app: traefik
      metrics: enabled
  podMetricsEndpoints:
  - port: metrics
