apiVersion: v2
description: A Helm chart for kavita
name: kavita
version: 1.0.0
# https://github.com/Kareadita/Kavita/releases
# renovate: image=jvmilazz0/kavita
appVersion: 0.8.2

dependencies:
  - name: common
    repository: https://bernd-schorgers.github.io/helm-charts 
    version: 3.4.0
