# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.0.1/charts/library/common/values.yaml
# https://github.com/bjw-s/helm-charts/blob/common-3.1.0/charts/library/common/values.yaml
controllers:
  main:
    strategy: RollingUpdate
    rollingUpdate:
        unavailable: 1
        surge: 0
    containers:
      main:
        image:
          repository: jvmilazz0/kavita
          pullPolicy: IfNotPresent
          tag: "{{ .Chart.AppVersion }}"
        env:
          TZ: "Europe/Helsinki"
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true

service:
  main:
    controller: main
    ports:
      http:
        port: 5000

persistence:
  data:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/kavita/data
    globalMounts:
      - path: /kavita/config

  book:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume2/book
    globalMounts:
      - path: /media/book
