apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    project: cicd
  name: cicd
  namespace: cicd
spec:
  description: CICD Project
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
