# https://github.com/k8s-at-home/charts/blob/paperless-9.1.3/charts/stable/paperless/values.yaml
paperless:
  image:
    # -- image repository
    repository: ghcr.io/paperless-ngx/paperless-ngx
    # -- image pull policy
    pullPolicy: IfNotPresent
    # -- image tag
    # @default -- chart.appVersion
    tag: 1.8.0
  env:
    TZ: "Europe/Helsinki"
    # -- Project name
    COMPOSE_PROJECT_NAME: paperless
    # -- Redis to use
    PAPERLESS_REDIS: redis://paperless-redis-headless:6379
    # -- OCR languages to install
    PAPERLESS_OCR_LANGUAGE: eng+kor
    # USERMAP_UID: 1000
    # USERMAP_GID: 1000
    PAPERLESS_TIME_ZONE: Europe/Helsinki
    # -- Database host to use
    # PAPERLESS_DBHOST: 
    # -- Port to use
    PAPERLESS_PORT: 8000
    # -- Username for the root user
    # PAPERLESS_ADMIN_USER: admin
    # -- Password for the root user
    # PAPERLESS_ADMIN_PASSWORD: admin
    # PAPERLESS_URL: <set to main ingress by default>
  persistence:
    data:
      enabled: true
      type: nfs
      server: 192.168.50.195
      path: /volume1/Paperless/data
      mountPath: /usr/src/paperless/data
      accessMode: ReadWriteOnce
    media:
      enabled: true
      type: nfs
      server: 192.168.50.195
      path: /volume1/Paperless/media
      mountPath: /usr/src/paperless/media
      accessMode: ReadWriteOnce
    consume:
      enabled: true
      type: nfs
      server: 192.168.50.195
      path: /volume1/Paperless/consume
      mountPath: /usr/src/paperless/consume
      accessMode: ReadWriteOnce
    export:
      enabled: true
      type: nfs
      server: 192.168.50.195
      path: /volume1/Paperless/export
      mountPath: /usr/src/paperless/export
      accessMode: ReadWriteOnce

  # -- Enable and configure redis subchart under this key.
  #    For more options see [redis chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/redis)
  # @default -- See values.yaml
  redis:
    enabled: true
    global:
      storageClass: nfs-client
    auth:
      enabled: false
