# https://github.com/bjw-s/helm-charts/tree/93e761fd99fb6eaad188173de6a6a3a57811ed25/charts/library/common
image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  pullPolicy: IfNotPresent
controller:
  strategy: RollingUpdate
  rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
env:
  TZ: "Europe/Helsinki"
  COMPOSE_PROJECT_NAME: paperless
  PAPERLESS_REDIS: redis://redis-master.persistence:6379
  PAPERLESS_OCR_LANGUAGES: fin kor
  PAPERLESS_OCR_LANGUAGE: eng+fin+kor
  USERMAP_UID: 1000
  USERMAP_GID: 1000
  PAPERLESS_TIME_ZONE: Europe/Helsinki
  PAPERLESS_DBHOST: postgresql.persistence
  PAPERLESS_PORT: 8000
  PAPERLESS_CONSUMER_POLLING: 300
envFrom:
  - secretRef:
      name: paperless-secrets
service:
  main:
    ports:
      http:
        port: 8000
persistence:
  data:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/paperless/data
    mountPath: /usr/src/paperless/data
    accessMode: ReadWriteOnce
  media:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/paperless/media
    mountPath: /usr/src/paperless/media
    accessMode: ReadWriteOnce
  consume:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume2/shared/Paperless
    mountPath: /usr/src/paperless/consume
    accessMode: ReadWriteOnce
  export:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/paperless/export
    mountPath: /usr/src/paperless/export
    accessMode: ReadWriteOnce
resources:
  limits:
    cpu: 128m
    memory: 1.5Gi
  requests:
    cpu: 16m
    memory: 1Gi
