{{- if and .Values.wikijs.enabled .Values.monitoring.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: wikijs
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: wikijs
      rules:
        - alert: WikiJsUnavailable
          expr: kube_deployment_status_replicas_available{namespace="services", deployment="wikijs"} < 1
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: Wiki.js knowledge base is unavailable
{{- end }}
