apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    project: messaging
  name: messaging
  namespace: cicd
spec:
  description: Messaging Project
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
