# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.0.1/charts/library/common/values.yaml
defaultPodOptions:
  hostNetwork: true
  securityContext:
    fsGroup: 999

controllers:
  main:
    containers:
      main:
        image:
          repository: jacobalberty/unifi
          pullPolicy: IfNotPresent
          tag: "{{ .Chart.AppVersion }}"
        env:
          TZ: "Europe/Helsinki"
          RUNAS_UID0: "false"
          UNIFI_UID: "999"
          UNIFI_GID: "999"
          JVM_INIT_HEAP_SIZE:
          JVM_MAX_HEAP_SIZE: 1024M
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              failureThreshold: 3
              initialDelaySeconds: 0
              periodSeconds: 10
              tcpSocket:
                port: 8443
              timeoutSeconds: 1
          readiness:
            enabled: true
            custom: true
            spec:
              failureThreshold: 3
              initialDelaySeconds: 0
              periodSeconds: 10
              tcpSocket:
                port: 8443
              timeoutSeconds: 1
          startup:
            enabled: true
            custom: true
            spec:
              failureThreshold: 3
              initialDelaySeconds: 0
              periodSeconds: 10
              tcpSocket:
                port: 8443
              timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
  backup:
    type: cronjob
    cronjob:
      backoffLimit: 3
      concurrencyPolicy: Forbid
      failedJobsHistory: 3
      schedule: "0 6 * * *" # daily at 6:00 utc
      startingDeadlineSeconds: 30
      successfulJobsHistory: 3
      suspend: false
    podSpec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - unifi
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - main
              topologyKey: "kubernetes.io/hostname"
    containers:
      main:
        image:
          repository: alpine
          tag: latest
        command:
          - sh
          - -c
          - |
            tar -czvf /backups/backups.tar.gz -C / unifi/data/backup/autobackup

service:
  main:
    controller: main
    type: LoadBalancer
    loadBalancerIP: "172.20.0.131"
    ports:
      http:
        port: 443
        protocol: HTTPS
        targetPort: 8443
      controller:
        enabled: true
        port: 8080
        protocol: TCP
      speedtest:
        enabled: true
        port: 6789
        protocol: TCP
      stun:
        enabled: true
        port: 3478
        protocol: UDP
      syslog:
        enabled: true
        port: 5514
        protocol: UDP
      discovery:
        enabled: true
        port: 10001
        protocol: UDP
persistence:
  data:
    enabled: true
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /unifi
    size: "5Gi"
  backup:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/backups/unifi
    advancedMounts:
      backup:
        main:
          - path: /backups
