# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.0.1/charts/library/common/values.yaml
controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/ddclient
          pullPolicy: IfNotPresent
          tag: "{{ .Chart.AppVersion }}"
        resources:
          limits:
            cpu: 30m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
persistence:
  config:
    enabled: true
    type: secret
    name: ddclient-secret
    defaultMode: 0600
