apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-loki
  labels:
    app.kubernetes.io/name: pv-loki
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: diskstation.local
    path: /volume1/LTS/monitoring/loki
