apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-postgres-cronjob
  namespace: persistence
spec:
  schedule: "30 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              registry: ghcr.io
              repository: seungbemi/bitnami-postgres-pgvector-rs
              tag: 14.5.0-v0.2.0
              command: ["/bin/sh", "-c"]
              args:
                - pg_dumpall -f /backups/postgres.pgdump -h postgresql -U postgres
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secrets
                      key: postgres-password
              volumeMounts:
                - mountPath: /backups
                  name: backups
          restartPolicy: Never
          volumes:
            - name: backups
              nfs:
                path: /volume1/LTS/backups
                server: diskstation.local
      backoffLimit: 4
