apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    project: services
  name: services
  namespace: cicd
spec:
  description: Services Project
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
