# https://github.com/bitnami/charts/blob/9e15346368a58970bfe079d242e8ea78bc2618ef/bitnami/postgresql/values.yaml
postgresql:
  auth:
    existingSecret: postgres-secrets
  shmVolume:
    enabled: false
  volumePermissions:
    enabled: false
  primary:
    persistence:
      enabled: true
      storageClass: ceph-block
      size: 8Gi
    initdb:
      scriptsSecret: "postgres-initscript"
