# https://github.com/bitnami/charts/blob/9e15346368a58970bfe079d242e8ea78bc2618ef/bitnami/postgresql/values.yaml
postgresql:
  image:
    registry: ghcr.io
    repository: seungbemi/bitnami-postgres-pgvector-rs
    tag: 14.18.0-vchord1.1.1
  auth:
    database: homeassistant
    existingSecret: postgres-secrets
  shmVolume:
    enabled: false
  volumePermissions:
    enabled: false
  primary:
    persistence:
      enabled: true
      storageClass: ceph-block
      size: 8Gi
    initdb:
      scriptsSecret: "postgres-initscript"
    resources:
      limits:
        memory: 1.5Gi
        cpu: 250m
      requests:
        memory: 1Gi
        cpu: 50m
  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/postgres-exporter
      tag: 0.17.1-debian-12-r16
    serviceMonitor:
      enabled: true
