---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
spec:
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      containers:
      - name: kavita
        image: kizaing/kavita:0.6.1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Europe/Helsinki

        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - mountPath: /media/book
          name: book
          readOnly: true
        - mountPath: /kavita/config
          name: data
          subPath: data

      restartPolicy: Always
      volumes:
      - name: book
        nfs:
          path: /volume2/book
          readOnly: true
          server: diskstation.local
      - name: data
        nfs:
          path: /volume1/LTS/kavita
          server: diskstation.local
          
