# https://github.com/grafana/helm-charts/blob/loki-stack-2.8.2/charts/loki-stack/values.yaml
loki-stack:
  # https://github.com/grafana/helm-charts/blob/loki-stack-2.8.2/charts/loki/values.yaml
  loki:
    isDefault: false
    persistence:
      enabled: true
      existingClaim: pv-claim-loki
    serviceMonitor:
      enabled: true
      interval: 1m
  # https://github.com/grafana/helm-charts/blob/loki-stack-2.8.2/charts/promtail/values.yaml
  # promtail:
