# https://github.com/grafana/helm-charts/blob/loki-stack-2.10.2/charts/loki-stack/values.yaml
loki-stack:
  # https://github.com/grafana/loki/blob/v2.7.3/production/helm/loki/values.yaml
  loki:
    isDefault: false
    persistence:
      enabled: false
      accessModes:
      - ReadWriteOnce
      size: 15Gi
      selector:
        matchLabels:
          app.kubernetes.io/name: pv-loki
    serviceMonitor:
      enabled: true
      interval: 1m
    resources:
      limits:
        memory: 320Mi
        cpu: 150m
      requests:
        memory: 224Mi
        cpu: 50m
  # https://github.com/grafana/helm-charts/blob/loki-stack-2.9.9/charts/promtail/values.yaml
  promtail:
    resources: 
      limits:
        cpu: 128m
        memory: 320Mi
      requests:
        cpu: 64m
        memory: 192Mi
