# https://github.com/grafana/helm-charts/blob/loki-stack-2.9.9/charts/loki-stack/values.yaml
loki-stack:
  # https://github.com/grafana/loki/blob/v2.7.3/production/helm/loki/values.yaml
  loki:
    isDefault: false
    persistence:
      enabled: true
      accessModes:
      - ReadWriteOnce
      size: 15Gi
      selector:
        matchLabels:
          app.kubernetes.io/name: pv-loki
    serviceMonitor:
      enabled: true
      interval: 1m
    resources:
      limits:
        memory: 300Mi
        cpu: 150m
      requests:
        memory: 150Mi
        cpu: 50m
  # https://github.com/grafana/helm-charts/blob/loki-stack-2.9.9/charts/promtail/values.yaml
  promtail:
    resources: 
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 30m
        memory: 150Mi
