# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json
# https://github.com/bjw-s/helm-charts/blob/common-3.1.0/charts/library/common/values.yaml
controllers:
  main:
    containers:
      main:
        image:
          repository: photoprism/photoprism
          pullPolicy: IfNotPresent
          tag: "{{ .Chart.AppVersion }}"
        env:
          TZ: "Europe/Helsinki"
          PHOTOPRISM_READONLY: "true"
          PHOTOPRISM_CACHE_PATH: /assets/cache
          PHOTOPRISM_IMPORT_PATH: /assets/photos/import
          PHOTOPRISM_EXPORT_PATH: /assets/photos/export
          PHOTOPRISM_STORAGE_PATH: /assets/storage
          PHOTOPRISM_BACKUP_PATH: /assets/backup
          PHOTOPRISM_ORIGINALS_PATH: /assets/photos/originals
          PHOTOPRISM_DATABASE_DRIVER: mysql
          PHOTOPRISM_HTTP_HOST: 0.0.0.0
          PHOTOPRISM_HTTP_PORT: "2342"
        envFrom:
          - secretRef:
              name: photoprism-secrets
              optional: false
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
        resources:
          requests:
            cpu: 32m
            memory: 512Mi
service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8000
        protocol: TCP
        targetPort: 2342

persistence:
  original:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume2/photo
    advancedMounts:
      main:
        main:
          - path: /assets/photos/originals
            readOnly: true
  cache:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/photoprism/cache
    globalMounts:
      - path: /assets/cache

  storage:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/photoprism/storage
    globalMounts:
      - path: /assets/storage

  import:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/photoprism/import
    globalMounts:
      - path: /assets/photos/import

  export:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/photoprism/export
    globalMounts:
      - path: /assets/photos/export
