apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-replica
  labels:
    app.kubernetes.io/name: pv-redis-replica
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: diskstation.local
    path: /volume1/LTS/redis-replica
