apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    project: kube-system
  name: kube-system
  namespace: cicd
spec:
  description: Kube-System Project
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
