---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:10.8.8
        imagePullPolicy: IfNotPresent
        env:
        - name: JELLYFIN_DATA_DIR
          value: "/data"
        - name: JELLYFIN_CONFIG_DIR
          value: "/config"
        - name: JELLYFIN_CACHE_DIR
          value: "/cache"
        envFrom:
        - secretRef:
            name: jellyfin-secrets
            optional: false
        ports:
        - containerPort: 8096
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: jellyfin
          subPath: data
        - mountPath: /cache
          name: jellyfin
          subPath: cache
        - mountPath: /config
          name: jellyfin
          subPath: config
        - mountPath: /media/video
          name: video
          readOnly: true
        - mountPath: /media/music
          name: music
          readOnly: true

      restartPolicy: Always
      volumes:
      - name: video
        nfs:
          path: /volume2/video
          readOnly: true
          server: diskstation.local
      - name: music
        nfs:
          path: /volume2/music
          readOnly: true
          server: diskstation.local
      - name: jellyfin
        nfs:
          path: /volume1/LTS/jellyfin
          server: diskstation.local
