---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:10.8.8
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: JELLYFIN_DATA_DIR
          value: "/data"
        - name: JELLYFIN_CONFIG_DIR
          value: "/config"
        - name: JELLYFIN_CACHE_DIR
          value: "/cache"
        envFrom:
        - secretRef:
            name: jellyfin-secrets
            optional: false
        ports:
        - containerPort: 8096
          protocol: TCP
        volumeMounts:
        - mountPath: /data/video
          name: video
          readOnly: True
        - mountPath: /data/music
          name: music
          readOnly: True
        - mountPath: /data/transcodes
          name: transcodes
        - mountPath: /data/metadata
          name: metadata
        - mountPath: /cache
          name: cache
        - mountPath: /config
          name: jellyfin-config
      restartPolicy: Always
      volumes:
      - name: video
        nfs:
          path: /volume2/video
          readOnly: true
          server: diskstation.local
      - name: music
        nfs:
          path: /volume2/music
          readOnly: true
          server: diskstation.local
      - name: cache
        nfs:
          path: /volume1/LTS/jellyfin/cache
          server: diskstation.local
      - name: metadata
        nfs:
          path: /volume1/LTS/jellyfin/metadata
          server: diskstation.local
      - name: transcodes
        nfs:
          path: /volume1/LTS/jellyfin/transcodes
          server: diskstation.local
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config
