# https://github.com/bitnami/charts/blob/redis/19.6.2/bitnami/redis/values.yaml
redis:
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: 7.2.5-debian-12-r2
  auth:
    enabled: false
  architecture: standalone
  master:
    persistence:
      storageClass: ceph-block
    resources:
      limits:
        memory: 256Mi
        cpu: 256m
      requests:
        memory: 64Mi
        cpu: 24m
