# https://github.com/bitnami/charts/blob/9e15346368a58970bfe079d242e8ea78bc2618ef/bitnami/redis/values.yaml
redis:
  auth:
    enabled: false
  architecture: standalone
  master:
    persistence:
      storageClass: ceph-block
    resources:
      limits:
        memory: 256Mi
        cpu: 256m
      requests:
        memory: 64Mi
        cpu: 24m

