kind: Service
apiVersion: v1
metadata:
  labels:
    app: wireguard
  name: wireguard-service
spec:
  type: LoadBalancer
  ports:
  - name: wg
    port: 51820
    protocol: UDP
    targetPort: 51820
  loadBalancerIP: "192.168.50.246"
  selector:
    app: wireguard
