# https://github.com/bjw-s/helm-charts/tree/93e761fd99fb6eaad188173de6a6a3a57811ed25/charts/library/common
image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
controller:
  strategy: RollingUpdate
  rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

env:
  TZ: "Europe/Helsinki"

hostNetwork: true

service:
  main:
    type: LoadBalancer
    loadBalancerIP: "172.20.0.132"
    ports:
      http:
        port: 8123

serviceMonitor:
  main:
    enabled: true
    endpoints:
    - port: http
      path: /api/prometheus
      bearerTokenSecret:
        key: token
        name: ha-prometheus

securityContext:
  privileged:  true

persistence:
  config:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/coder/caffeine/Caffeine/home-assistant
    accessMode: ReadWriteOnce
  usb:
    enabled: true
    type: hostPath
    hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2233659-if00

resources:
  requests:
    cpu: 50m
    memory: 1000Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: zigbee-node
          operator: In
          values:
          - "true"
