# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json
# https://github.com/bjw-s/helm-charts/blob/common-3.1.0/charts/library/common/values.yaml
defaultPodOptions:
  hostNetwork: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: zigbee-node
                operator: In
                values:
                  - "true"

controllers:
  main:
    containers:
      main:
        image:
          repository: homeassistant/home-assistant
          pullPolicy: IfNotPresent
          tag: "{{ .Chart.AppVersion }}"
        env:
          TZ: "Europe/Helsinki"
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
        securityContext:
          privileged: true
  unison:
    type: cronjob
    cronjob:
      backoffLimit: 6
      concurrencyPolicy: Forbid
      failedJobsHistory: 1
      schedule: "* * * * *"
      startingDeadlineSeconds: 30
      successfulJobsHistory: 1
      suspend: false
    containers:
      main:
        image:
          repository: onnimonni/unison
          tag: latest
        command:
        - sh
        - -c
        - |
          unison -batch /config /config-nfs

service:
  main:
    controller: main
    type: LoadBalancer
    loadBalancerIP: "172.20.0.132"
    ports:
      http:
        port: 8123

serviceMonitor:
  main:
    serviceName: home-assistant
    enabled: true
    endpoints:
      - port: http
        path: /api/prometheus
        bearerTokenSecret:
          key: token
          name: ha-prometheus

persistence:
  config:
    enabled: true
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: "1Gi"
    globalMounts:
      - path: /config
  config-nfs:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/coder/caffeine/Caffeine/home-assistant
    globalMounts:
      - path: /config-nfs
  usb:
    enabled: true
    type: hostPath
    hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2233659-if00

resources:
  requests:
    cpu: 50m
    memory: 1000Mi
