apiVersion: v1
kind: Service
metadata:
  name: ha-service
spec:
  ports:
    - name: ha
      protocol: TCP
      port: 8123
      targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ha-service
subsets:
  - addresses:
      - ip: {{ .Values.homeAssistantIP }}
    ports:
      - name: ha
        port: 8123
