{{- range .Values.webServices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  ports:
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .name }}-service
  labels:
    kubernetes.io/service-name: {{ .name }}-service
addressType: FQDN
ports:
  - name: {{ .name }}
    port: {{ .port }}
endpoints:
  - addresses:
      - {{ $.Values.defaultDomain }}
{{- end }}
