apps:
  - name: applications
    namespace: cicd
    path: kubernetes/cicd/applications
    sync: true

# https://github.com/argoproj/argo-helm/blob/argo-cd-5.20.3/charts/argo-cd/values.yaml
argo-cd:
  controller:
    enableStatefulSet: true
    args:
      # -- define the application controller `--status-processors`
      statusProcessors: "40"
      # -- define the application controller `--operation-processors`
      operationProcessors: "20"
      # -- define the application controller `--repo-server-timeout-seconds`
      repoServerTimeoutSeconds: "300"
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
  
  server:
    extraArgs:
      - --insecure
    autoscaling:
      enabled: true
      minReplicas: 1
      targetCPUUtilizationPercentage: 90
      targetMemoryUtilizationPercentage: 90
    resources: 
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 100Mi
    config:
      admin.enabled: "false"
      accounts.seungbemi: apiKey, login
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, seungbemi, role:admin
    secret:
      createSecret: false

  dex:
    enabled: false

  repoServer:
    replicas: 2
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 64Mi

  applicationSet:
    enabled: false

  notifications:
    # TODO : configure slack notification
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 50Mi
  