apiVersion: batch/v1
kind: CronJob
metadata:
  name: set-inform-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: set-inform
              image: kroniak/ssh-client:3.15
              command: ["/bin/bash", "-c"]
              args:
                - hosts=($HOSTS);
                  for host in "${hosts[@]}";
                  do
                      echo "${host}";
                      ssh -o "StrictHostKeyChecking=no" $USERNAME@$host -i /unifi/unifi "mca-cli-op info" | grep http://unifi.lan:8080/inform;
                      [ $? == 1 ] && ssh -o "StrictHostKeyChecking=no" $USERNAME@$host -i /unifi/unifi "mca-cli-op set-inform http://unifi.lan:8080/inform";
                  done;
                  exit 0;
              envFrom:
              - secretRef:
                  name: unifi
              volumeMounts:
              - mountPath: "/unifi"
                name: ssh-key
          restartPolicy: Never
          volumes:
            - name: ssh-key
              secret:
                secretName: unifi-controller-ssh-key
                defaultMode: 256
      backoffLimit: 0
