apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: 1.0.0
appVersion: v1.0.0

# https://github.com/cert-manager/cert-manager/blob/v1.15.1/deploy/charts/cert-manager/Chart.template.yaml
dependencies:
- name: cert-manager
  version: v1.17.1
  repository: https://charts.jetstack.io
