apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager

type: application

version: 1.13.2
appVersion: v1.13.2

dependencies:
- name: cert-manager
  version: 1.13.2
  repository: https://charts.jetstack.io
