# https://github.com/cert-manager/cert-manager/blob/v1.15.1/deploy/charts/cert-manager/values.yaml
cert-manager: 
  installCRDs: true
  resources:
    limits:
      cpu: 30m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      interval: 1m
  webhook:
    hostNetwork: true
    securePort: 10255
    resources:
      limits:
        cpu: 30m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
  cainjector:
      resources:
        limits:
          cpu: 30m
          memory: 200Mi
        requests:
          cpu: 10m
          memory: 100Mi
