{{- if .Values.configHelper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-config-helper
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: config-helper
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/controller: main
  ports:
    - name: https
      protocol: TCP
      port: 8444
      targetPort: 8444
{{- end }}
