apiVersion: v2
name: metrics-server
description: Metrics Server is a scalable, efficient source of container resource metrics for Kubernetes built-in autoscaling pipelines.
type: application
version: 3.8.2
appVersion: 0.6.1

dependencies:
- name: metrics-server
  version: 3.8.2
  repository: https://kubernetes-sigs.github.io/metrics-server/
