apiVersion: v2
name: metrics-server
description: Metrics Server is a scalable, efficient source of container resource metrics for Kubernetes built-in autoscaling pipelines.
type: application
version: 1.0.0
appVersion: v1.0.0

# https://github.com/kubernetes-sigs/metrics-server/blob/v0.7.1/charts/metrics-server/Chart.yaml
dependencies:
- name: metrics-server
  version: 3.13.0
  repository: https://kubernetes-sigs.github.io/metrics-server/
