apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    project: monitoring
  name: monitoring
  namespace: cicd
spec:
  description: Monitoring Project
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
