# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json
# https://github.com/bjw-s/helm-charts/blob/common-3.1.0/charts/library/common/values.yaml
controllers:
  main:
    containers:
      main:
        image:
          repository: eclipse-mosquitto
          pullPolicy: IfNotPresent
          tag: "{{ .Chart.AppVersion }}"
        env:
          TZ: "Europe/Helsinki"
          USERMAP_UID: 1000
          USERMAP_GID: 1000
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              failureThreshold: 30
              initialDelaySeconds: 0
              periodSeconds: 5
              tcpSocket:
                port: 1883
              timeoutSeconds: 1
          readiness:
            enabled: true
            custom: true
            spec:
              failureThreshold: 30
              initialDelaySeconds: 0
              periodSeconds: 5
              tcpSocket:
                port: 1883
              timeoutSeconds: 1
          startup:
            enabled: true
            custom: true
            spec:
              failureThreshold: 30
              initialDelaySeconds: 0
              periodSeconds: 5
              tcpSocket:
                port: 1883
              timeoutSeconds: 1


service:
  main:
    controller: main
    ports:
      main:
        enabled: true
        port: 1883


persistence:
  data:
    enabled: true
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /mosquitto/data
    size: "1Gi"
  config:
    enabled: true
    type: configMap
    name: mosquitto-config
    globalMounts:
      - path: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
    defaultMode: 384
  password:
    enabled: true
    type: configMap
    name: mosquitto-password
    globalMounts:
      - path: /mosquitto/config/password.txt
        subPath: password.txt
