# https://github.com/bjw-s/helm-charts/tree/93e761fd99fb6eaad188173de6a6a3a57811ed25/charts/library/common
image:
  repository: eclipse-mosquitto
  pullPolicy: IfNotPresent
# controller:
#   strategy: RollingUpdate
#   rollingUpdate:
#       maxUnavailable: 1
#       maxSurge: 0
env:
  TZ: "Europe/Helsinki"
  USERMAP_UID: 1000
  USERMAP_GID: 1000

service:
  main:
    ports:
      http:
        enabled: false
      main:
        enabled: true
        port: 1883


probes:
  liveness:
    enabled: true
    type: tcp
    port: 1883
  readiness:
    enabled: true
    type: tcp
    port: 1883
  startup:
    enabled: true
    type: tcp
    port: 1883

persistence:
  data:
    enabled: true
    storageClass: ceph-block
    mountPath: "/mosquitto/data"
    accessMode: ReadWriteOnce
    size: "1Gi"
  config:
    enabled: true
    type: configMap
    name: mosquitto-config
    subPath: mosquitto.conf
    mountPath: /mosquitto/config/mosquitto.conf
    defaultMode: 384
  password:
    enabled: true
    type: configMap
    name: mosquitto-password
    subPath: password.txt
    mountPath: /mosquitto/config/password.txt
