apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    project: persistence
  name: persistence
  namespace: cicd
spec:
  description: Persistence Project
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
