# https://github.com/bitnami/charts/blob/c227f808331712bff5cceeb2e7e5bb7b84675ae7/bitnami/mariadb/values.yaml
mariadb:
  initdbScriptsConfigMap: mariadb-initscript
  auth:
    username: mariadb
    existingSecret: mariadb-secrets
  primary:
    persistence:
      storageClass: ceph-block
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
