{
 "title": "Data Center",
 "tags": [ "data center" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Data Center", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_sensor_power_w{entity=\"sensor.server_plug_active_power\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost Per Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (increase(ha_sensor_monetary_eur{entity=\"sensor.server_plug_summation_delivered_cost_2\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_sensor_power_w{entity=\"sensor.server_plug_active_power\"})",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "Mikrotik",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (ha_sensor_unit_percent{service=\"home-assistant\", entity=~\"sensor.mikrotik_.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WLAN",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (ha_sensor_data_rate_b_per_s{entity=~\"sensor.mikrotik_ether1_rx|sensor.mikrotik_ether1_tx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WLAN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (ha_sensor_data_rate_b_per_s{entity=~\"sensor.mikrotik_ether1_rx|sensor.mikrotik_ether1_tx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VLAN",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (ha_sensor_data_rate_kb_per_s{entity=~\".*_vlan_.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk Station", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "DiskStation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_sensor_unit_percent{service=\"home-assistant\", entity=~\"sensor.funserviceds_.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DiskStation Network",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_sensor_data_rate_kb_per_s{service=\"home-assistant\", entity=~\"sensor.funserviceds_.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_sensor_unit_percent{service=\"home-assistant\", entity=~\"sensor.funserviceds_.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "K8s Master Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU load (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.124:9100\"})",
     "legendFormat": "master1"
    },
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.123:9100\"})",
     "legendFormat": "master2"
    },
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.108:9100\"})",
     "legendFormat": "master3"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.124:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.124:9100\"})\n* 100\n)",
     "legendFormat": "master1"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.123:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.123:9100\"})\n* 100\n)",
     "legendFormat": "master2"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.108:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.108:9100\"})\n* 100\n)",
     "legendFormat": "master3"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\nmax by (mountpoint) (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"172.20.0.124:9100\", fstype!=\"\", mountpoint=\"/\"}) / max by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", instance=\"172.20.0.124:9100\", fstype!=\"\", mountpoint=\"/\"})\n* 100\n)",
     "legendFormat": "master1"
    },
    {
     "expr": "100 -\n(\nmax by (mountpoint) (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"172.20.0.123:9100\", fstype!=\"\", mountpoint=\"/\"}) / max by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", instance=\"172.20.0.123:9100\", fstype!=\"\", mountpoint=\"/\"})\n* 100\n)",
     "legendFormat": "master2"
    },
    {
     "expr": "100 -\n(\nmax by (mountpoint) (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"172.20.0.108:9100\", fstype!=\"\", mountpoint=\"/\"}) / max by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", instance=\"172.20.0.108:9100\", fstype!=\"\", mountpoint=\"/\"})\n* 100\n)",
     "legendFormat": "master3"
    }
   ]
  },
  {
   "title": "CPU load (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.124:9100\"})",
     "legendFormat": "master1"
    },
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.123:9100\"})",
     "legendFormat": "master2"
    },
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.108:9100\"})",
     "legendFormat": "master3"
    },
    { "expr": "100", "legendFormat": "MAX" }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.124:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.124:9100\"})\n* 100\n)",
     "legendFormat": "master1"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.123:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.123:9100\"})\n* 100\n)",
     "legendFormat": "master2"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.108:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.108:9100\"})\n* 100\n)",
     "legendFormat": "master3"
    },
    { "expr": "100", "legendFormat": "MAX" }
   ]
  },
  { "title": "K8s Worker Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "CPU load (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.127:9100\"})",
     "legendFormat": "worker1"
    },
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.126:9100\"})",
     "legendFormat": "worker2"
    },
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.125:9100\"})",
     "legendFormat": "worker3"
    },
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.112:9100\"})",
     "legendFormat": "worker4"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.127:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.127:9100\"})\n* 100\n)",
     "legendFormat": "worker1"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.126:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.126:9100\"})\n* 100\n)",
     "legendFormat": "worker2"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.125:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.125:9100\"})\n* 100\n)",
     "legendFormat": "worker3"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.112:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.112:9100\"})\n* 100\n)",
     "legendFormat": "worker4"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\nmax by (mountpoint) (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"172.20.0.127:9100\", fstype!=\"\", mountpoint=\"/\"}) / max by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", instance=\"172.20.0.127:9100\", fstype!=\"\", mountpoint=\"/\"})\n* 100\n)",
     "legendFormat": "worker1"
    },
    {
     "expr": "100 -\n(\nmax by (mountpoint) (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"172.20.0.126:9100\", fstype!=\"\", mountpoint=\"/\"}) / max by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", instance=\"172.20.0.126:9100\", fstype!=\"\", mountpoint=\"/\"})\n* 100\n)",
     "legendFormat": "worker2"
    },
    {
     "expr": "100 -\n(\nmax by (mountpoint) (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"172.20.0.125:9100\", fstype!=\"\", mountpoint=\"/\"}) / max by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", instance=\"172.20.0.125:9100\", fstype!=\"\", mountpoint=\"/\"})\n* 100\n)",
     "legendFormat": "worker3"
    },
    {
     "expr": "100 -\n(\nmax by (mountpoint) (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"172.20.0.112:9100\", fstype!=\"\", mountpoint=\"/\"}) / max by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", instance=\"172.20.0.112:9100\", fstype!=\"\", mountpoint=\"/\"})\n* 100\n)",
     "legendFormat": "worker4"
    }
   ]
  },
  {
   "title": "CPU load (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.127:9100\"})",
     "legendFormat": "worker1"
    },
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.126:9100\"})",
     "legendFormat": "worker2"
    },
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.125:9100\"})",
     "legendFormat": "worker3"
    },
    {
     "expr": "sum by(instance) (node_load1{job=\"node-exporter\", instance=\"172.20.0.112:9100\"})",
     "legendFormat": "worker4"
    },
    { "expr": "100", "legendFormat": "MAX" }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.127:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.127:9100\"})\n* 100\n)",
     "legendFormat": "worker1"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.126:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.126:9100\"})\n* 100\n)",
     "legendFormat": "worker2"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.125:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.125:9100\"})\n* 100\n)",
     "legendFormat": "worker3"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"172.20.0.112:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"172.20.0.112:9100\"})\n* 100\n)",
     "legendFormat": "worker4"
    },
    { "expr": "100", "legendFormat": "MAX" }
   ]
  }
 ]
}