{
 "title": "Home Assistant",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature (°C)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_temperature_c{service=\"home-assistant\", entity!~\"sensor.bekgomds_deuraibeu_1_temperature|sensor.bekgomds_deuraibeu_2_temperature|sensor.bekgomds_temperature\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_humidity_percent{service=\"home-assistant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure (hPa)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_pressure_hPa{service=\"home-assistant\"})",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Power Consumption (W)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_sensor_power_w{service=\"home-assistant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Router Network Speed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_sensor_unit_mbit_per_s{service=\"home-assistant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (ha_temperature_c{service=\"home-assistant\", entity!~\"sensor.bekgomds_deuraibeu_1_temperature|sensor.bekgomds_deuraibeu_2_temperature|sensor.bekgomds_temperature\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (ha_humidity_percent{service=\"home-assistant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (ha_pressure_hPa{service=\"home-assistant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_sensor_power_w{service=\"home-assistant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Router Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum by(entity) (ha_sensor_unit_mbit_per_s{service=\"home-assistant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Usage (%)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(entity) (ha_sensor_unit_percent{service=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Speed",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 11, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(entity) (ha_sensor_unit_kb_per_s{service=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(entity) (ha_sensor_unit_percent{service=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Speed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum by(entity) (ha_sensor_unit_kb_per_s{service=\"home-assistant\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}