apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-mariadb-cronjob
  namespace: persistence
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: bitnami/mariadb:10.6.11-debian-11-r12
              command: ["/bin/sh", "-c"]
              args:
                - mysqldump --host=mariadb -uroot --lock-tables --all-databases --result-file=/backup/mariadb.sql
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: mariadb-secrets
                      key: mariadb-root-password
              volumeMounts:
                - mountPath: /backup
                  name: database
                  subPath: mariadb
          restartPolicy: Never
          volumes:
            - name: database
              nfs:
                path: /volume1/LTS/database
                server: diskstation.local
      backoffLimit: 4
