---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.0.1/charts/library/common/values.yaml
controllers:
  main:
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: 1
      surge: 0
    containers:
      main:
        image:
          repository: adguard/adguardhome
          pullPolicy: IfNotPresent
          tag: "{{ .Chart.AppVersion }}"
        env:
          TZ: Europe/Helsinki
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              failureThreshold: 30
              initialDelaySeconds: 0
              periodSeconds: 5
              tcpSocket:
                port: 3000
              timeoutSeconds: 1
          readiness:
            enabled: true
            custom: true
            spec:
              failureThreshold: 30
              initialDelaySeconds: 0
              periodSeconds: 5
              tcpSocket:
                port: 3000
              timeoutSeconds: 1
          startup:
            enabled: true
            custom: true
            spec:
              failureThreshold: 30
              initialDelaySeconds: 0
              periodSeconds: 5
              tcpSocket:
                port: 3000
              timeoutSeconds: 1
        resources:
          requests:
            cpu: 16m
            memory: 96Mi

  backup:
    type: cronjob
    cronjob:
      backoffLimit: 3
      concurrencyPolicy: Forbid
      failedJobsHistory: 3
      schedule: "0 3 * * *" # daily at 3:00 utc
      startingDeadlineSeconds: 30
      successfulJobsHistory: 3
      suspend: false
    pod:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - adguard
                  - key: app.kubernetes.io/controller
                    operator: In
                    values:
                      - main
              topologyKey: "kubernetes.io/hostname"
    containers:
      main:
        image:
          repository: alpine
          tag: latest
        command:
          - sh
          - -c
          - |
            tar -czvf /opt/adguardhome/backups/backups.tar.gz -C /opt/adguardhome conf

service:
  main:
    controller: main
    primary: true
    type: LoadBalancer
    loadBalancerIP: "172.20.0.129"
    ports:
      http:
        enabled: true
        port: 3000
        protocol: TCP
        targetPort: 3000
      dns:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
persistence:
  config-backup:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/backups/adguardhome
    globalMounts:
      - path: /opt/adguardhome/backups
  config:
    enabled: true
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: "50Mi"
    globalMounts:
      - path: /opt/adguardhome/conf
