---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json
# https://github.com/bjw-s/helm-charts/blob/common-3.1.0/charts/library/common/values.yaml
controllers:
  main:
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: 1
      surge: 0
    containers:
      main:
        image:
          repository: adguard/adguardhome
          pullPolicy: IfNotPresent
          tag: "{{ .Chart.AppVersion }}"
        env:
          TZ: Europe/Helsinki
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              failureThreshold: 30
              initialDelaySeconds: 0
              periodSeconds: 5
              tcpSocket:
                port: 3000
              timeoutSeconds: 1
          readiness:
            enabled: true
            custom: true
            spec:
              failureThreshold: 30
              initialDelaySeconds: 0
              periodSeconds: 5
              tcpSocket:
                port: 3000
              timeoutSeconds: 1
          startup:
            enabled: true
            custom: true
            spec:
              failureThreshold: 30
              initialDelaySeconds: 0
              periodSeconds: 5
              tcpSocket:
                port: 3000
              timeoutSeconds: 1
        resources:
          requests:
            cpu: 16m
            memory: 96Mi
      temp:
        image:
          repository: alpine
          tag: latest
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]

service:
  main:
    controller: main
    primary: true
    type: LoadBalancer
    loadBalancerIP: "172.20.0.129"
    ports:
      http:
        enabled: true
        port: 3000
        protocol: TCP
        targetPort: 3000
      dns:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
persistence:
  config-nfs:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/adguardhome/config
    globalMounts: 
      - path: /opt/adguardhome/conf
  config:
    enabled: true
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: "50Mi"
    globalMounts:
      - path: /opt/adguardhome/conf-new
