# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.0.1/charts/library/common/values.yaml
# https://github.com/bjw-s/helm-charts/blob/common-3.1.0/charts/library/common/values.yaml
controllers:
  main:
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: 1
      surge: 0
    containers:
      main:
        image:
          repository: masipcat/wireguard-go
          pullPolicy: IfNotPresent
          tag: "{{ .Chart.AppVersion }}"
        env:
          TZ: "Europe/Helsinki"
          LOG_LEVEL: info
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false
        resources:
          requests:
            memory: 64Mi
            cpu: "100m"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true


    initContainers:
      sysctls:
        image: 
          repository: busybox
          tag: latest
        command:
        - sh
        - -c
        - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true

service:
  main:
    controller: main
    type: LoadBalancer
    loadBalancerIP: "172.20.0.130"
    ports:
      http:
        enabled: false
        port: 80
      wg:
        primary: true
        port: 51820
        protocol: UDP
        targetPort: 51820

persistence:
  config:
    enabled: true
    type: configMap
    name: wg-configmap
    globalMounts:
      - path: /etc/wireguard/wg0.conf
        subPath: wg0.conf
    defaultMode: 384
  secret:
    enabled: true
    type: secret
    name: wg-secret
    globalMounts:
      - path: /etc/wireguard/privatekey
        subPath: privatekey
    defaultMode: 384
