# https://github.com/bjw-s/helm-charts/tree/93e761fd99fb6eaad188173de6a6a3a57811ed25/charts/library/common
image:
  repository: masipcat/wireguard-go
  pullPolicy: IfNotPresent
controller:
  strategy: RollingUpdate
  rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
env:
  TZ: "Europe/Helsinki"
  LOG_LEVEL: info

securityContext:
  capabilities:
    add:
      - NET_ADMIN
  privileged:  true

initContainers:
  sysctls:
    image: busybox
    command:
    - sh
    - -c
    - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
      privileged: true
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
service:
  main:
    type: LoadBalancer
    loadBalancerIP: "172.20.0.130"
    ports:
      http:
        enabled: false
      wg:
        primary: true
        port: 51820
        protocol: UDP
        targetPort: 51820

persistence:
  config:
    enabled: true
    type: configMap
    name: wg-configmap
    subPath: wg0.conf
    mountPath: /etc/wireguard/wg0.conf
    defaultMode: 384
  secret:
    enabled: true
    type: secret
    name: wg-secret
    subPath: privatekey
    mountPath: /etc/wireguard/privatekey
    defaultMode: 384

resources:
  requests:
    memory: 64Mi
    cpu: "100m"
  limits:
    memory: 256Mi
