apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome
  labels:
    app: adguardhome
spec:
  storageClassName: ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
