# https://github.com/rook/rook/blob/v1.12.9/deploy/charts/rook-ceph/values.yaml
rook-ceph:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 128Mi
  monitoring:
    enabled: true
  csi:
    csiRBDProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 50m
        - name : csi-resizer
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 50m
        - name : csi-attacher
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 50m
        - name : csi-snapshotter
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 50m
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 100m
        - name : csi-omap-generator
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 50m
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 100m
    csiRBDPluginResource: |
      - name : driver-registrar
        resource:
          requests:
            memory: 64Mi
            cpu: 10m
          limits:
            memory: 256Mi
            cpu: 50m
      - name : csi-rbdplugin
        resource:
          requests:
            memory: 64Mi
            cpu: 10m
          limits:
            memory: 256Mi
            cpu: 100m
      - name : liveness-prometheus
        resource:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
    # -- CEPH CSI CephFS provisioner resource requirement list
    # @default -- see values.yaml
    csiCephFSProvisionerResource: |
      - name : csi-provisioner
        resource:
          requests:
            memory: 128Mi
            cpu: 10m
          limits:
            memory: 256Mi
            cpu: 50m
      - name : csi-resizer
        resource:
          requests:
            memory: 128Mi
            cpu: 10m
          limits:
            memory: 256Mi
            cpu: 50m
      - name : csi-attacher
        resource:
          requests:
            memory: 128Mi
            cpu: 10m
          limits:
            memory: 256Mi
            cpu: 50m
      - name : csi-snapshotter
        resource:
          requests:
            memory: 64Mi
            cpu: 10m
          limits:
            memory: 256Mi
            cpu: 50m
      - name : csi-cephfsplugin
        resource:
          requests:
            memory: 64Mi
            cpu: 10m
          limits:
            memory: 256Mi
            cpu: 100m
      - name : liveness-prometheus
        resource:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
    # -- CEPH CSI CephFS plugin resource requirement list
    # @default -- see values.yaml
    csiCephFSPluginResource: |
      - name : driver-registrar
        resource:
          requests:
            memory: 128Mi
            cpu: 10m
          limits:
            memory: 256Mi
            cpu: 50m
      - name : csi-cephfsplugin
        resource:
          requests:
            memory: 64Mi
            cpu: 10m
          limits:
            memory: 256Mi
            cpu: 100m
      - name : liveness-prometheus
        resource:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
# https://github.com/rook/rook/blob/v1.12.9/deploy/charts/rook-ceph-cluster/values.yaml
rook-ceph-cluster:
  operatorNamespace: persistence
  monitoring:
    enabled: true
  cephClusterSpec:
    placement:
      all:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: ceph-node
                  operator: In
                  values:
                  - "true"
    mon:
      count: 3
      allowMultiplePerNode: false
    mgr:
      count: 2
    dashboard:
      enabled: true
      ssl: false
    crashCollector:
      disable: true
    logCollector:
      enabled: false
    resources:
      mgr:
        limits:
          cpu: "500m"
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "500Mi"
      mon:
        limits:
          cpu: "500m"
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "256Mi"
      osd:
        limits:
          cpu: "250m"
          memory: "3Gi"
        requests:
          cpu: "100m"
          memory: "1.5Gi"
  cephBlockPools:
  - name: ceph-blockpool
    spec:
      failureDomain: host
      replicated:
        size: 3
      deviceClass: "ssd"
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: false
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      mountOptions: []
      parameters:
        imageFormat: "2"
        imageFeatures: layering
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: persistence
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: persistence
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: persistence
        csi.storage.k8s.io/fstype: ext4
  cephFileSystems:
  - name: ceph-filesystem
    # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem-crd.md#filesystem-settings for available configuration
    spec:
      metadataPool:
        replicated:
          size: 3
      dataPools:
        - failureDomain: host
          replicated:
            size: 3
          name: data0
      metadataServer:
        activeCount: 1
        activeStandby: true
    storageClass:
      enabled: true
      isDefault: false
      name: ceph-filesystem
      pool: data0
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      mountOptions: []
      parameters:
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: persistence
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: persistence
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: persistence
        csi.storage.k8s.io/fstype: ext4
