apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-immich
  labels:
    app.kubernetes.io/name: pv-immich
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: diskstation.local
    path: /volume1/LTS/immich

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich
  labels:
    app.kubernetes.io/name: pvc-immich
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: pv-immich


