# https://github.com/bjw-s/helm-charts/tree/93e761fd99fb6eaad188173de6a6a3a57811ed25/charts/library/common
image:
  repository: ghcr.io/blakeblackshear/frigate
  pullPolicy: IfNotPresent
controller:
  strategy: RollingUpdate
  rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
env:
  TZ: "Europe/Helsinki"
envFrom:
  - secretRef:
      name: frigate-secrets

service:
  main:
    ports:
      http:
        port: 5000
      rtsp:
        port: 8554
      rtmp:
        port: 1935

configMaps:
  # -- frigate configuration - see [Docs](https://docs.frigate.video/configuration/index) for more info
  config:
    enabled: true
    labels:
      app: frigate
    data:
      config.yml: |
        mqtt:
          host: mosquitto.messaging
          port: 1883
          topic_prefix: frigate
          client_id: frigate
          # Optional: user
          user: "{FRIGATE_MQTT_USER}"
          password: "{FRIGATE_MQTT_PASSWORD}"
          stats_interval: 60
        detectors:
          cpu1:
            type: cpu
        record:
          enabled: true
          events:
            retain:
              default: 14
              mode: active_objects
        snapshots:
          enabled: true
          crop: true
          height: 175
          retain:
            default: 10
            objects:
              person: 15
        go2rtc:
          streams:
            front_door:
              - rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_RTSP_HOST_CAM1}:554/cam/realmonitor?channel=1&subtype=0
        cameras:
          front_door:
            ffmpeg:
              inputs:
                - path: rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_RTSP_HOST_CAM1}:554/cam/realmonitor?channel=1&subtype=2
                  roles:
                    - detect
                - path: rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_RTSP_HOST_CAM1}:554/cam/realmonitor?channel=1&subtype=0
                  roles:
                    - record
                    - rtmp
            motion:
              mask:
                - 342,0,1280,0,1280,298,1254,357,547,40,343,67
persistence:
  data:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/frigate
    mountPath: /media/frigate
    accessMode: ReadWriteOnce
  config:
    enabled: true
    type: configMap
    name: frigate-config
    subPath: config.yml
    mountPath: /config/config.yml
    defaultMode: 384
  shm:
    enabled: true
    type: emptyDir
    mountPath: /dev/shm
    sizeLimit: 1Gi
    medium: Memory
# resources:
#   limits:
#     cpu: 1
#     memory: 1.5Gi
#   requests:
#     cpu: 16m
#     memory: 1Gi
