# https://github.com/bjw-s/helm-charts/tree/93e761fd99fb6eaad188173de6a6a3a57811ed25/charts/library/common
image:
  repository: ghcr.io/blakeblackshear/frigate
  pullPolicy: IfNotPresent
controller:
  strategy: RollingUpdate
  rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
env:
  TZ: "Europe/Helsinki"
envFrom:
  - secretRef:
      name: frigate-secrets

service:
  main:
    ports:
      http:
        port: 5000
      rtsp:
        port: 8554

persistence:
  data:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/frigate
    mountPath: /media/frigate
    accessMode: ReadWriteOnce
  config:
    enabled: true
    type: configMap
    name: frigate-config
    subPath: config.yml
    mountPath: /config/config.yml
    defaultMode: 384
  shm:
    enabled: true
    type: emptyDir
    mountPath: /dev/shm
    sizeLimit: 1Gi
    medium: Memory
# resources:
#   limits:
#     cpu: 1
#     memory: 1.5Gi
#   requests:
#     cpu: 16m
#     memory: 1Gi
