# https://github.com/bjw-s/helm-charts/tree/93e761fd99fb6eaad188173de6a6a3a57811ed25/charts/library/common
image:
  repository: ghcr.io/blakeblackshear/frigate
  pullPolicy: IfNotPresent
controller:
  strategy: RollingUpdate
  rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
env:
  TZ: "Europe/Helsinki"
envFrom:
  - secretRef:
      name: frigate-secrets

initContainers:
  init-config:
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        cp /tmp/config/config.yml /config/config.yml
    volumeMounts:
      - name: config
        mountPath: /tmp/config/config.yml
        subPath: config.yml
      - name: config-folder
        mountPath: /config
service:
  main:
    ports:
      http:
        port: 5000
      rtsp:
        port: 8554
      rtmp:
        port: 1935

securityContext:
  privileged:  true

configMaps:
  # -- frigate configuration - see [Docs](https://docs.frigate.video/configuration/index) for more info
  config:
    enabled: true
    labels:
      app: frigate
    data:
      config.yml: |
        mqtt:
          host: mosquitto.messaging
          port: 1883
          topic_prefix: frigate
          client_id: frigate
          # Optional: user
          user: "{FRIGATE_MQTT_USER}"
          password: "{FRIGATE_MQTT_PASSWORD}"
          stats_interval: 60
        detectors:
          coral:
            type: edgetpu
            device: usb
        ffmpeg:
          hwaccel_args: preset-vaapi
        record:
          enabled: true
          events:
            retain:
              default: 14
              mode: active_objects
        snapshots:
          enabled: true
          crop: true
          height: 175
          retain:
            default: 14
            objects:
              person: 15
        go2rtc:
          streams:
            front_door:
              - rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_RTSP_HOST_CAM1}:554/cam/realmonitor?channel=1&subtype=0
            front_door_sub:
              - rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_RTSP_HOST_CAM1}:554/cam/realmonitor?channel=1&subtype=2
            back_door:
              - rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_RTSP_HOST_CAM2}:554/cam/realmonitor?channel=1&subtype=0
            back_door_sub:
              - rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_RTSP_HOST_CAM2}:554/cam/realmonitor?channel=1&subtype=2
        cameras:
          front_door:
            ffmpeg:
              inputs:
                - path: rtsp://127.0.0.1:8554/front_door_sub
                  roles:
                    - detect
                - path: rtsp://127.0.0.1:8554/front_door
                  roles:
                    - record
                    - rtmp
            motion:
              mask:
                - 342,0,1280,0,1280,298,1254,357,547,40,343,67
          back_door:
            ffmpeg:
              inputs:
                - path: rtsp://127.0.0.1:8554/back_door_sub
                  roles:
                    - detect
                - path: rtsp://127.0.0.1:8554/back_door
                  roles:
                    - record
                    - rtmp
            motion:
              mask:
                - 1280,0,1248,196,1038,108,1017,256,577,100,585,0
persistence:
  data:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/frigate
    mountPath: /media/frigate
    accessMode: ReadWriteOnce
  config-folder:
    enabled: true
    type: nfs
    server: diskstation.local
    path: /volume1/LTS/frigate/config
    mountPath: /config
    accessMode: ReadWriteOnce
  config:
    enabled: true
    type: configMap
    name: frigate-config
    subPath: config.yml
    mountPath: /tmp/config/config.yml
    defaultMode: 384
  shm:
    enabled: true
    type: emptyDir
    mountPath: /dev/shm
    sizeLimit: 1Gi
    medium: Memory
  tpu:
    enabled: true
    type: hostPath
    hostPath: /dev/bus/usb
  hwaccel:
    enabled: true
    type: hostPath
    hostPath: /dev/dri/renderD128
# resources:
#   limits:
#     cpu: 1
#     memory: 1.5Gi
#   requests:
#     cpu: 16m
#     memory: 1Gi
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: coral-tpu-node
          operator: In
          values:
          - "true"
