apps:
  - name: cicd
    namespace: cicd
    path: kubernetes/cicd/argocd
    sync: true

  - name: renovatebot
    namespace: cicd
    path: kubernetes/cicd/renovatebot
    sync: true

  - name: cicd-secrets
    namespace: cicd
    repoURL: git@github.com:seungbemi/gitops-secrets.git
    path: kubernetes/cicd/secrets
    sync: true

  - name: monitoring
    namespace: monitoring
    path: kubernetes/monitoring/_project
    sync: true
  
  - name: ingress
    namespace: ingress
    path: kubernetes/ingress/_project
    sync: true

  - name: persistence
    namespace: persistence
    path: kubernetes/persistence/_project
    sync: true

  - name: kube-system
    namespace: kube-system
    path: kubernetes/kube-system/_project
    sync: true

  - name: messaging
    namespace: messaging
    path: kubernetes/messaging/_project
    sync: true

  - name: services
    namespace: services
    path: kubernetes/services/_project
    sync: true
